//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Freshop97.Droid.Servicio1 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IService1", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback historialOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultaDatosPantalonOperationCompleted;
        
        private System.Threading.SendOrPostCallback transaccionOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultaProductoOperationCompleted;
        
        private System.Threading.SendOrPostCallback inicioSesionOperationCompleted;
        
        private System.Threading.SendOrPostCallback registrarUsuarioOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = "http://www.freshop977.somee.com/Service1.svc";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event historialCompletedEventHandler historialCompleted;
        
        /// <remarks/>
        public event consultaDatosPantalonCompletedEventHandler consultaDatosPantalonCompleted;
        
        /// <remarks/>
        public event transaccionCompletedEventHandler transaccionCompleted;
        
        /// <remarks/>
        public event consultaProductoCompletedEventHandler consultaProductoCompleted;
        
        /// <remarks/>
        public event inicioSesionCompletedEventHandler inicioSesionCompleted;
        
        /// <remarks/>
        public event registrarUsuarioCompletedEventHandler registrarUsuarioCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/historial", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataTable historial(int idx, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idxSpecified) {
            object[] results = this.Invoke("historial", new object[] {
                        idx,
                        idxSpecified});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void historialAsync(int idx, bool idxSpecified) {
            this.historialAsync(idx, idxSpecified, null);
        }
        
        /// <remarks/>
        public void historialAsync(int idx, bool idxSpecified, object userState) {
            if ((this.historialOperationCompleted == null)) {
                this.historialOperationCompleted = new System.Threading.SendOrPostCallback(this.OnhistorialOperationCompleted);
            }
            this.InvokeAsync("historial", new object[] {
                        idx,
                        idxSpecified}, this.historialOperationCompleted, userState);
        }
        
        private void OnhistorialOperationCompleted(object arg) {
            if ((this.historialCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.historialCompleted(this, new historialCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/consultaDatosPantalon", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] consultaDatosPantalon(int idx, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idxSpecified) {
            object[] results = this.Invoke("consultaDatosPantalon", new object[] {
                        idx,
                        idxSpecified});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void consultaDatosPantalonAsync(int idx, bool idxSpecified) {
            this.consultaDatosPantalonAsync(idx, idxSpecified, null);
        }
        
        /// <remarks/>
        public void consultaDatosPantalonAsync(int idx, bool idxSpecified, object userState) {
            if ((this.consultaDatosPantalonOperationCompleted == null)) {
                this.consultaDatosPantalonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaDatosPantalonOperationCompleted);
            }
            this.InvokeAsync("consultaDatosPantalon", new object[] {
                        idx,
                        idxSpecified}, this.consultaDatosPantalonOperationCompleted, userState);
        }
        
        private void OnconsultaDatosPantalonOperationCompleted(object arg) {
            if ((this.consultaDatosPantalonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaDatosPantalonCompleted(this, new consultaDatosPantalonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/transaccion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string transaccion(int id_usuario, [System.Xml.Serialization.XmlIgnoreAttribute()] bool id_usuarioSpecified, int id_producto, [System.Xml.Serialization.XmlIgnoreAttribute()] bool id_productoSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string id_empresa, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string date, int cantidad, [System.Xml.Serialization.XmlIgnoreAttribute()] bool cantidadSpecified) {
            object[] results = this.Invoke("transaccion", new object[] {
                        id_usuario,
                        id_usuarioSpecified,
                        id_producto,
                        id_productoSpecified,
                        id_empresa,
                        date,
                        cantidad,
                        cantidadSpecified});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void transaccionAsync(int id_usuario, bool id_usuarioSpecified, int id_producto, bool id_productoSpecified, string id_empresa, string date, int cantidad, bool cantidadSpecified) {
            this.transaccionAsync(id_usuario, id_usuarioSpecified, id_producto, id_productoSpecified, id_empresa, date, cantidad, cantidadSpecified, null);
        }
        
        /// <remarks/>
        public void transaccionAsync(int id_usuario, bool id_usuarioSpecified, int id_producto, bool id_productoSpecified, string id_empresa, string date, int cantidad, bool cantidadSpecified, object userState) {
            if ((this.transaccionOperationCompleted == null)) {
                this.transaccionOperationCompleted = new System.Threading.SendOrPostCallback(this.OntransaccionOperationCompleted);
            }
            this.InvokeAsync("transaccion", new object[] {
                        id_usuario,
                        id_usuarioSpecified,
                        id_producto,
                        id_productoSpecified,
                        id_empresa,
                        date,
                        cantidad,
                        cantidadSpecified}, this.transaccionOperationCompleted, userState);
        }
        
        private void OntransaccionOperationCompleted(object arg) {
            if ((this.transaccionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.transaccionCompleted(this, new transaccionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/consultaProducto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
        public int[] consultaProducto(int categoria, [System.Xml.Serialization.XmlIgnoreAttribute()] bool categoriaSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string tipo_s) {
            object[] results = this.Invoke("consultaProducto", new object[] {
                        categoria,
                        categoriaSpecified,
                        tipo_s});
            return ((int[])(results[0]));
        }
        
        /// <remarks/>
        public void consultaProductoAsync(int categoria, bool categoriaSpecified, string tipo_s) {
            this.consultaProductoAsync(categoria, categoriaSpecified, tipo_s, null);
        }
        
        /// <remarks/>
        public void consultaProductoAsync(int categoria, bool categoriaSpecified, string tipo_s, object userState) {
            if ((this.consultaProductoOperationCompleted == null)) {
                this.consultaProductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaProductoOperationCompleted);
            }
            this.InvokeAsync("consultaProducto", new object[] {
                        categoria,
                        categoriaSpecified,
                        tipo_s}, this.consultaProductoOperationCompleted, userState);
        }
        
        private void OnconsultaProductoOperationCompleted(object arg) {
            if ((this.consultaProductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaProductoCompleted(this, new consultaProductoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/inicioSesion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] inicioSesion([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string email, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string contraseña) {
            object[] results = this.Invoke("inicioSesion", new object[] {
                        email,
                        contraseña});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void inicioSesionAsync(string email, string contraseña) {
            this.inicioSesionAsync(email, contraseña, null);
        }
        
        /// <remarks/>
        public void inicioSesionAsync(string email, string contraseña, object userState) {
            if ((this.inicioSesionOperationCompleted == null)) {
                this.inicioSesionOperationCompleted = new System.Threading.SendOrPostCallback(this.OninicioSesionOperationCompleted);
            }
            this.InvokeAsync("inicioSesion", new object[] {
                        email,
                        contraseña}, this.inicioSesionOperationCompleted, userState);
        }
        
        private void OninicioSesionOperationCompleted(object arg) {
            if ((this.inicioSesionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.inicioSesionCompleted(this, new inicioSesionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/registrarUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string registrarUsuario([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string nom, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string ap, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string am, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string tel, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string email, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string contraseña, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string edo, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string ciudad, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string colonia, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string calle, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string nm, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string cp) {
            object[] results = this.Invoke("registrarUsuario", new object[] {
                        nom,
                        ap,
                        am,
                        tel,
                        email,
                        contraseña,
                        edo,
                        ciudad,
                        colonia,
                        calle,
                        nm,
                        cp});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void registrarUsuarioAsync(string nom, string ap, string am, string tel, string email, string contraseña, string edo, string ciudad, string colonia, string calle, string nm, string cp) {
            this.registrarUsuarioAsync(nom, ap, am, tel, email, contraseña, edo, ciudad, colonia, calle, nm, cp, null);
        }
        
        /// <remarks/>
        public void registrarUsuarioAsync(string nom, string ap, string am, string tel, string email, string contraseña, string edo, string ciudad, string colonia, string calle, string nm, string cp, object userState) {
            if ((this.registrarUsuarioOperationCompleted == null)) {
                this.registrarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregistrarUsuarioOperationCompleted);
            }
            this.InvokeAsync("registrarUsuario", new object[] {
                        nom,
                        ap,
                        am,
                        tel,
                        email,
                        contraseña,
                        edo,
                        ciudad,
                        colonia,
                        calle,
                        nm,
                        cp}, this.registrarUsuarioOperationCompleted, userState);
        }
        
        private void OnregistrarUsuarioOperationCompleted(object arg) {
            if ((this.registrarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.registrarUsuarioCompleted(this, new registrarUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void historialCompletedEventHandler(object sender, historialCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class historialCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal historialCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void consultaDatosPantalonCompletedEventHandler(object sender, consultaDatosPantalonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaDatosPantalonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaDatosPantalonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void transaccionCompletedEventHandler(object sender, transaccionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class transaccionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal transaccionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void consultaProductoCompletedEventHandler(object sender, consultaProductoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaProductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaProductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void inicioSesionCompletedEventHandler(object sender, inicioSesionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class inicioSesionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal inicioSesionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void registrarUsuarioCompletedEventHandler(object sender, registrarUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class registrarUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal registrarUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591